### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by sauramaia** [HealthHackAu/website-2015#8]
we have a proposed logo from andre, need to make some decisions and upload it.

**Comment by mscook** [comment]
For reference - 

![health-hack-logo_acanthus-black](https://cloud.githubusercontent.com/assets/179770/8229049/db35692e-15f6-11e5-80ae-c08acc08532e.png)

![health-hack-logo_acanthus-light](https://cloud.githubusercontent.com/assets/179770/8229059/f4d99b3e-15f6-11e5-862e-641525eb7c2b.png)

**Comment by mscook** [comment]
I think the font needs to be changed & also Health Hack text needs to be Left or Right as at the moment the logo is stretched horizontally (IMO).

**Comment by sauramaia** [comment]
solution: keep logo as is.
